"""Changed win column in standings table to be nullable

Revision ID: 41bb42d97d3f
Revises: 5d7a2361f551
Create Date: 2019-02-18 08:12:37.377646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bb42d97d3f'
down_revision = '5d7a2361f551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_standing', 'wins',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_standing', 'wins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
