"""Created a relationship between weekly results and standings and the user table to get the display name.

Revision ID: 5d7a2361f551
Revises: 0e742dda0965
Create Date: 2019-02-17 07:41:09.873176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7a2361f551'
down_revision = '0e742dda0965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_result', 'user')
    op.drop_column('weekly_standing', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_standing', sa.Column('user', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('weekly_result', sa.Column('user', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
