"""added active and visible columns to pick table

Revision ID: b5af0c6fa611
Revises: 7c469ed02f7c
Create Date: 2019-03-01 20:07:41.251661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5af0c6fa611'
down_revision = '7c469ed02f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick', sa.Column('active', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('pick', sa.Column('visible', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pick', 'visible')
    op.drop_column('pick', 'active')
    # ### end Alembic commands ###
