"""Added a foreign key to pick table to reference user table

Revision ID: f8086dc81122
Revises: 16afee7efe6a
Create Date: 2019-02-10 20:06:43.175585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8086dc81122'
down_revision = '16afee7efe6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pick', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.drop_column('pick', 'user_id')
    # ### end Alembic commands ###
